name: user
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.6.0
  google_sign_in: ^6.1.4
  injectable: ^2.1.2
  auto_route: ^7.4.0
  country_code_picker: ^3.0.0
  image_picker: ^0.8.9
  firebase_storage: ^11.2.3
  lazy_load_scrollview: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  build_runner: ^2.4.5
  injectable_generator: ^2.1.6
  auto_route_generator: ^7.1.1
  pinput: ^2.2.31

flutter:
  uses-material-design: true

  assets:
    - assets/images/
